import {parseMatrix,format,multiply,transpose,hadamard,kron,sparsity,classifyStructure,memoryModel,traceCell,estimateOps,normalizeRows,slice,parseUploadedMatrix} from './engine.js';
import {PUBLIC_DATASETS} from './public-data.js';
const $=s=>document.querySelector(s); const Ael=$('#A'),Bel=$('#B'),out=$('#out'),stats=$('#stats'),extra=$('#extra'),sourcePanel=$('#sourcePanel');
const fmt=A=>A.map(r=>r.join(' ')).join('\n');
function safe(fn){try{fn()}catch(e){out.textContent='Error: '+e.message;stats.innerHTML='';extra.innerHTML=''}}
function matrixViz(A){const rows=A.slice(0,12),cols=Math.min(12,A[0]?.length||0);return `<div class="viz" style="--cols:${cols}">${rows.flatMap(r=>r.slice(0,cols)).map(v=>`<div class="cell ${v===0?'zero':''}">${Number(Number(v).toFixed(3))}</div>`).join('')}</div>${A.length>12||A[0].length>12?'<p class="note">Preview limited to 12 × 12 cells.</p>':''}`}
function showSource(d){sourcePanel.hidden=false;sourcePanel.innerHTML=`<b>${d.name}</b> · ${d.provider}<br><span class="note">Original shape ${d.fullShape[0]} × ${d.fullShape[1]}; this reproducible browser sample is ${d.sampleShape[0]} × ${d.sampleShape[1]}.</span><br><a href="${d.source}" target="_blank" rel="noopener">Open public source ↗</a>`}
function loadPublic(id){const d=PUBLIC_DATASETS.find(x=>x.id===id);if(!d)return;Ael.value=fmt(d.A);Bel.value=fmt(transpose(d.A));showSource(d);run();window.scrollTo({top:document.querySelector('.workspace').offsetTop-20,behavior:'smooth'})}
window.loadPublic=loadPublic;
function renderGallery(){const q=($('#datasetSearch')?.value||'').trim().toLowerCase();const provider=$('#datasetProvider')?.value||'';const list=PUBLIC_DATASETS.filter(d=>(!provider||d.provider===provider)&&(!q||[d.name,d.provider,d.domain,d.description,d.sampleMethod||''].join(' ').toLowerCase().includes(q)));$('#datasetGrid').innerHTML=list.map(d=>`<article class="dataset-card"><h3>${d.name}</h3><div class="meta">${d.provider} · ${d.domain} · ${d.fullShape[0]}×${d.fullShape[1]}</div><p>${d.description}</p><p class="note">Browser sample: ${d.sampleShape[0]}×${d.sampleShape[1]} · ${d.sampleMethod||'reproducible numeric view'}</p><div class="actions"><button data-load="${d.id}">Load sample</button><a href="${d.source}" target="_blank" rel="noopener">Source ↗</a></div></article>`).join('');document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadPublic(b.dataset.load));$('#datasetCount').textContent=`${list.length} / ${PUBLIC_DATASETS.length} datasets`}
$('#datasetSearch').oninput=renderGallery;if($('#datasetProvider'))$('#datasetProvider').onchange=renderGallery;renderGallery();
function run(){safe(()=>{const A=parseMatrix(Ael.value),B=parseMatrix(Bel.value),mode=document.body.dataset.mode;let C,html='';if(mode==='matmulx'){C=multiply(A,B);const o=estimateOps(A,B);out.textContent=format(C);stats.innerHTML=`<div class=stat><span>Output shape</span><b>${C.length}×${C[0].length}</b></div><div class=stat><span>Dense multiplies</span><b>${o.denseMult.toLocaleString()}</b></div><div class=stat><span>Zero multiplies skipped</span><b>${o.skipped.toLocaleString()}</b></div>`;html='<h2>Output preview</h2>'+matrixViz(C)}else if(mode==='matrixmorph'){const op=$('#operation').value;if(op==='transpose')C=transpose(A);if(op==='hadamard')C=hadamard(A,B);if(op==='kron')C=kron(A,B);if(op==='normalize')C=normalizeRows(A);if(op==='slice')C=slice(A,0,Math.min(8,A.length),0,Math.min(8,A[0].length));out.textContent=format(C);stats.innerHTML=`<div class=stat><span>Input</span><b>${A.length}×${A[0].length}</b></div><div class=stat><span>Output</span><b>${C.length}×${C[0].length}</b></div><div class=stat><span>Operation</span><b>${op}</b></div>`;html='<h2>Visual result</h2>'+matrixViz(C)}else if(mode==='sparsescope'){const s=sparsity(A),m=memoryModel(A),c=classifyStructure(A);out.textContent=JSON.stringify({shape:[A.length,A[0].length],sparsity:+(s*100).toFixed(3)+'%',structure:c,denseBytes:m.denseBytes,csrBytes:m.csrBytes,recommended:s>0.65?'CSR / sparse representation':'Dense representation'},null,2);stats.innerHTML=`<div class=stat><span>Sparsity</span><b>${(s*100).toFixed(1)}%</b></div><div class=stat><span>Dense est.</span><b>${m.denseBytes.toLocaleString()} B</b></div><div class=stat><span>CSR est.</span><b>${m.csrBytes.toLocaleString()} B</b></div>`;html='<h2>Sparsity preview</h2>'+matrixViz(A)}else{C=multiply(A,B);const i=Math.min(Number($('#traceRow')?.value||0),C.length-1),j=Math.min(Number($('#traceCol')?.value||0),C[0].length-1),t=traceCell(A,B,i,j);out.textContent=format(C);stats.innerHTML=`<div class=stat><span>Inspecting</span><b>C[${i},${j}]</b></div><div class=stat><span>Terms</span><b>${t.terms.length}</b></div><div class=stat><span>Result</span><b>${Number(t.sum.toFixed(6))}</b></div>`;html='<h2>Computation trace</h2><div class=trace>'+t.terms.map(x=>`<div>A[${i},${x.k}] × B[${x.k},${j}] = ${x.a} × ${x.b} = <b>${Number(x.product.toFixed(6))}</b></div>`).join('')+`<div><b>Sum = ${Number(t.sum.toFixed(6))}</b></div></div>`}extra.innerHTML=html})}
$('#run').onclick=run; if($('#operation'))$('#operation').onchange=run; if($('#traceRow'))$('#traceRow').oninput=run;if($('#traceCol'))$('#traceCol').oninput=run;
async function loadFile(input,target){const f=input.files?.[0];if(!f)return;const text=await f.text();const A=parseUploadedMatrix(text,f.name);target.value=fmt(A);sourcePanel.hidden=false;sourcePanel.innerHTML=`<b>Your data</b> · ${f.name}<br><span class="note">Parsed locally in your browser as ${A.length} × ${A[0].length}. The file is not uploaded to a server.</span>`;run()}
$('#uploadA').onchange=e=>safe(()=>loadFile(e.target,Ael));$('#uploadB').onchange=e=>safe(()=>loadFile(e.target,Bel));
$('#download').onclick=()=>safe(()=>{const text=out.textContent;if(!text||text.startsWith('Error:'))throw new Error('Run an analysis first.');const blob=new Blob([text],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='matrix-result.txt';a.click();URL.revokeObjectURL(a.href)});
loadPublic('sk-iris');
